// Maps a resolved public image path (e.g. "/pins/sf-moma.PNG") to the
// small WebP derivative generated by scripts/optimize-images.mjs
// ("/pins/optimized/thumb/sf-moma.webp"). Vector placeholders are already
// tiny, so they pass through untouched.
function derivedPath(path: string, tier: 'thumb' | 'full') {
  if (path.endsWith('.svg')) return path;
  const lastSlash = path.lastIndexOf('/');
  const dir = path.slice(0, lastSlash);
  const file = path.slice(lastSlash + 1);
  const base = file.replace(/\.[^.]+$/, '');
  return `${dir}/optimized/${tier}/${base}.webp`;
}

export function thumbImage(path: string) { return derivedPath(path, 'thumb'); }
export function fullImage(path: string) { return derivedPath(path, 'full'); }
